name: "Hashnode Blog"

env:
  hashnode_username: 'devid'
  count: 6

on:
  # workflow_dispatch:
  # schedule:
  # - cron: "0 12 * * *"


jobs:
  update_demo:
    name: "Update Latest Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📥  blog"
        uses: "varunsridharan/action-hashnode-blog@1.1.1"
        with:
          USERNAME: ${{ env.hashnode_username }}
          COUNT: ${{ env.count }}
          FILE: "README.md"
          STYLE: "blog-grid-4"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
